# Generated by Django 4.0.6 on 2022-07-17 01:39

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ag', models.CharField(max_length=25)),
                ('num_ag', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etu', models.CharField(max_length=25)),
                ('prenom_etu', models.CharField(max_length=25)),
                ('dt_nai_etu', models.DateField()),
                ('dt_iscri_etu', models.DateField()),
                ('lieu_nai_etu', models.CharField(max_length=25)),
                ('sexe_etu', models.CharField(max_length=25)),
                ('adresse_etu', models.TextField(max_length=25)),
                ('image_etu', models.ImageField(blank=True, null=True, upload_to=App.models.get_name)),
                ('classe_etu', models.CharField(max_length=25)),
                ('an_sco', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etu', models.CharField(max_length=25)),
                ('prix', models.IntegerField(max_length=25)),
                ('dt_pay', models.DateField()),
            ],
        ),
    ]
