# Generated by Django 4.0.6 on 2022-07-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frais',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
