# Generated by Django 4.0.6 on 2022-07-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_frais_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_sco_nom', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Etu_classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_nom', models.CharField(max_length=25)),
                ('ann_sco', models.CharField(max_length=25)),
            ],
        ),
    ]
