# Generated by Django 4.0.6 on 2022-07-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_annescolaire_etu_classe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nom_ag',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='num_ag',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='frais',
            name='ann_sco',
            field=models.CharField(default='', max_length=25),
        ),
    ]
