# Generated by Django 4.0.6 on 2022-07-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_delete_agent_etudiant_nom_ag_etudiant_num_ag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_abs', models.DateField()),
                ('ann_sco', models.CharField(max_length=25)),
                ('justification', models.CharField(max_length=30)),
                ('etu_id', models.CharField(max_length=30)),
            ],
        ),
    ]
