# Generated by Django 4.0.6 on 2022-07-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_matier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etu_nt', models.CharField(max_length=25)),
                ('an_nt', models.CharField(max_length=25)),
                ('cl_nt', models.CharField(max_length=25)),
                ('matier_nt', models.CharField(max_length=25)),
                ('dev_nt', models.FloatField(max_length=10)),
                ('ex_nt', models.FloatField(max_length=10)),
            ],
        ),
    ]
